config/routes.rb
Journal::Application.routes.draw do

  root to: 'entries#index'

  resources :entries
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_numericality_of :category_id

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_cats, only: [:show, :edit, :update]

  def index
    @categories = Category.all
  end

  def show
  end

  # creating new cats
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(cat_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created!'
    else
      render action:'new'
    end
  end

  #editting the cat
  def edit
  end

  def update
    if @category.update(cat_params)
      redirect_to categories_path, notice: 'Category was successfully updated!'
    else
      render action: 'edit'
    end
  end

  #destroy a cat
  def destroy
    if Category.destroy(params[:id])
       redirect_to categories_path
    else
      redirect_to categories_path, notice: 'WARNING: The category was not destroyed'
    end
  end


  private

  def set_cats
    @category = Category.find(params[:id])
  end

  def cat_params
    params.require(:category).permit(:name)
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, except: [:index, :new, :create, :destroy]

# Make new entries
  def new
    @entry = Entry.new
  end

  def create
    if params["entry"][:title].empty?
      raise 'WARNING: Entry not valid. Missing title.'
    elsif params["entry"][:description].empty?
      raise 'WARNING: Entry not valid. Missing description.'
    end
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to @entry, notice: 'Entry was successfully created!'
    else
      render action:'new'
    end
  end

  # Show the entries
  def show
    @entry = Entry.find(params[:id])
  end

  def index
    @entries = Entry.all.order("created_at DESC")
  end

 #Edit the entries
  def edit
  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated!'
    else
      render action: 'edit'
    end
  end

 #destroy the entry
  def destroy
    if Entry.destroy(params[:id])
       redirect_to entries_path
    else
      redirect_to entries_path, notice: 'WARNING: The entry was not destroyed'
    end
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :description, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { class: 'form-horizontal' }) do |f| %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Back', entries_path, class: 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="form-actions">
  <h1>Edit a Category</h1>

</div>

<%= render 'form', object: @category %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<p>
  <%= link_to 'Add Category', new_category_path %>
</p>

<br />

<ul class="unstyled">
  <% @categories.each do |cat| %>
  <li>
    <%if cat.entries.count >= 1%>
      <%= link_to cat.name, category_path(cat) %>
    <%else%>
      <%= cat.name %>
    <%end%>
    <%= link_to 'Edit', edit_category_path(cat) %>
    <%= link_to 'Delete', category_path(cat), :method => 'delete' %>
  </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<div class="form-actions">
  <h1>Submit Category</h1>

</div>

<%= render 'form', object: @category %>

app/views/categories/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @category.name %>
</p>

<%@category.entries.each do |entry|%>
<p>
  <%= link_to entry.title, entry_path(entry)%>
</p>
<%end%>

<%= link_to 'Back', categories_path %>

app/views/entries/_form.html.erb
<%= form_for(@entry, html: { class: 'form-horizontal' }) do |f| %>

  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :category, class: 'control-label' %>
    <div class="controls">
      <%= f.collection_select(:category_id, Category.order(:name),:id,:name, include_blank: true) %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Back', entries_path, class: 'btn' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<%= render 'form', object: @entry %>

app/views/entries/index.html.erb
<h1>Journal</h1>

<p>
  <%= link_to 'Add Entry', new_entry_path %>
</p>

<br />

<ul class="unstyled">
  <% @entries.each do |entry| %>
  <li>
    <%= link_to entry.title, entry %>
  </li>
  <% end %>
</ul>

app/views/entries/new.html.erb
<div class="form-actions">
  <h1>Submit Entry</h1>

</div>

<%= render 'form', object: @entry %>

app/views/entries/show.html.erb
<p>
  <%= @entry.created_at.strftime('%B %Y, %I:%M%p') %>
</p>
<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>


<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>
<p>
<%= link_to @entry.category.name, category_path(@entry.category) unless @entry.category.nil? %>
</p>

<%= link_to 'Back', entries_path %>
<%= link_to 'Edit', edit_entry_path %>
<%= link_to 'Delete', entry_path, :method => 'delete' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>